/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const clockPanel: string;
declare const card: string;
declare const cardFlip: string;
declare const cardStatic: string;
declare const flipCardLeafFront: string;
declare const flipCardLeafBack: string;
declare const cardLeaf: string;
declare const cardContent: string;
declare const cardContentTop: string;
declare const cardContentBottom: string;

export {
	clockPanel,
	card,
	cardFlip,
	cardStatic,
	flipCardLeafFront,
	flipCardLeafBack,
	cardLeaf,
	cardContent,
	cardContentTop,
	cardContentBottom
};

declare const __default_export__: {
	clockPanel: typeof clockPanel;
	card: typeof card;
	cardFlip: typeof cardFlip;
	cardStatic: typeof cardStatic;
	flipCardLeafFront: typeof flipCardLeafFront;
	flipCardLeafBack: typeof flipCardLeafBack;
	cardLeaf: typeof cardLeaf;
	cardContent: typeof cardContent;
	cardContentTop: typeof cardContentTop;
	cardContentBottom: typeof cardContentBottom;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRmxpcENhcmQubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJGbGlwQ2FyZC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBSUE7Y0FNQTtjQVVBO2NBSUE7Y0FJQTtjQUlBO2NBSUE7Y0FPQTtjQU1BO2NBT0E7OztDQXBEQTtDQU1BO0NBVUE7Q0FJQTtDQUlBO0NBSUE7Q0FJQTtDQU9BO0NBTUE7Q0FPQTs7OztDQXBEQTtDQU1BO0NBVUE7Q0FJQTtDQUlBO0NBSUE7Q0FJQTtDQU9BO0NBTUE7Q0FPQTs7In0=
