/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const clock: string;

export {
	clock
};

declare const __default_export__: {
	clock: typeof clock;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ2xvY2subW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJDbG9jay5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7OztDQUFBOzs7O0NBQUE7OyJ9
